name: rizzume
description: "A new Flutter project."



version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  google_fonts: ^6.0.0
  flutter_widget_from_html: ^0.15.2
  webview_flutter: ^4.7.0
  url_launcher: ^6.3.1
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.1.0
  
  # Firebase
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.2
  firebase_storage: ^12.3.8
  image_picker: ^1.1.2
  flutter_image_compress: ^2.3.0
  
  # Video
  video_player: ^2.8.2
  video_compress: ^3.1.2
  path_provider: ^2.1.2
  visibility_detector: ^0.4.0+2
  
  # WebRTC P2P Chat
  flutter_webrtc: ^1.2.0
  socket_io_client: ^2.0.3+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.3.3
  connectivity_plus: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  
  # Build runner for Hive code generation
  build_runner: ^2.4.8
  hive_generator: ^2.0.1

  flutter_launcher_icons: ^0.10.0


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/neon_r.png"
  adaptive_icon_background: "#181616"
  remove_alpha_ios: true


flutter:
  uses-material-design: true


  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/html_pages/


  fonts:
    - family: SplineSans
      fonts:
        - asset: assets/fonts/SplineSans-Light.ttf
          weight: 300
        - asset: assets/fonts/SplineSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/SplineSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/SplineSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SplineSans-Bold.ttf
          weight: 700
